/**
 * @ils/types — shared domain model for İSTANBUL LIVE SEISMIC.
 * All timestamps are ISO-8601 strings in UTC unless stated otherwise.
 */

// ─────────────────────────────────────────────────────────────
// Sources & data classes
// ─────────────────────────────────────────────────────────────

/** Upstream data providers. MOCK exists only outside production and is always labelled. */
export type SourceId = 'AFAD' | 'KANDILLI' | 'MOCK' | 'OTHER';

export const SOURCE_IDS: SourceId[] = ['AFAD', 'KANDILLI', 'MOCK', 'OTHER'];

/**
 * Provenance class of a stored record:
 *  - live : ingested from a real upstream provider
 *  - seed : synthetic history created by `db:seed` (development only)
 *  - mock : generated by the mock development provider
 * Anything other than `live` must be visually labelled in the UI.
 */
export type DataClass = 'live' | 'seed' | 'mock';

export type SourceHealth = 'ONLINE' | 'DEGRADED' | 'OFFLINE' | 'DISABLED' | 'UNKNOWN';

// ─────────────────────────────────────────────────────────────
// GeoJSON (minimal structural types, RFC 7946 compatible)
// ─────────────────────────────────────────────────────────────

export type Position = [longitude: number, latitude: number];

export interface PointGeometry {
  type: 'Point';
  coordinates: Position;
}
export interface LineStringGeometry {
  type: 'LineString';
  coordinates: Position[];
}
export interface MultiLineStringGeometry {
  type: 'MultiLineString';
  coordinates: Position[][];
}
export interface PolygonGeometry {
  type: 'Polygon';
  coordinates: Position[][];
}
export type Geometry =
  | PointGeometry
  | LineStringGeometry
  | MultiLineStringGeometry
  | PolygonGeometry;

export interface Feature<G extends Geometry = Geometry, P = Record<string, unknown>> {
  type: 'Feature';
  geometry: G;
  properties: P;
  id?: string | number;
}
export interface FeatureCollection<G extends Geometry = Geometry, P = Record<string, unknown>> {
  type: 'FeatureCollection';
  features: Feature<G, P>[];
}

// ─────────────────────────────────────────────────────────────
// Earthquake — provider report (normalized provider output)
// ─────────────────────────────────────────────────────────────

/** A single normalized report as returned by a provider adapter. */
export interface EarthquakeReport {
  /** Stable id within the provider adapter (source-scoped). */
  id: string;
  source: SourceId;
  /** The provider's own event id when it exposes one. */
  sourceEventId?: string;
  /** UTC ISO timestamp of the event origin time. */
  occurredAt: string;
  latitude: number;
  longitude: number;
  depthKm: number;
  magnitude: number;
  magnitudeType?: string;
  location: string;
  dataClass?: DataClass;
  rawPayload?: unknown;
}

// ─────────────────────────────────────────────────────────────
// Earthquake — canonical stored event (post dedupe + enrichment)
// ─────────────────────────────────────────────────────────────

export interface EarthquakeSourceRecord {
  source: SourceId;
  sourceEventId: string;
  occurredAt: string;
  latitude: number;
  longitude: number;
  depthKm: number;
  magnitude: number;
  magnitudeType?: string;
  location: string;
  firstSeenAt: string;
  lastSeenAt: string;
}

export interface Earthquake {
  id: string;
  occurredAt: string;
  latitude: number;
  longitude: number;
  depthKm: number;
  magnitude: number;
  magnitudeType?: string;
  location: string;
  /** Preferred (authoritative) source for the canonical fields. */
  source: SourceId;
  dataClass: DataClass;
  /** All providers that reported this event (dedupe keeps every source). */
  sources: EarthquakeSourceRecord[];
  // ── spatial enrichment ──
  istanbulDistanceKm: number;
  nearestFaultId: string | null;
  nearestFaultSlug: string | null;
  nearestFaultName: string | null;
  nearestFaultDistanceKm: number | null;
  districtSlug: string | null;
  districtName: string | null;
  inIstanbul: boolean;
  inMarmaraSea: boolean;
  createdAt: string;
  updatedAt: string;
}

// ─────────────────────────────────────────────────────────────
// Fault segments
// ─────────────────────────────────────────────────────────────

export interface FaultSegment {
  id: string;
  name: string;
  slug: string;
  geometry: LineStringGeometry | MultiLineStringGeometry;
  segmentType: string;
  description: string;
  /** True when the geometry is a simplified/approximate digitization. */
  approximate: boolean;
  /** True for aggregate zones excluded from nearest-fault attribution. */
  isZone: boolean;
  source: string;
  sourceUrl: string;
  license: string;
  lastVerified: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface FaultStats {
  faultId: string;
  slug: string;
  name: string;
  counts: { h24: number; d7: number; d30: number; total: number };
  maxMagnitude: number | null;
  avgMagnitude: number | null;
  avgDepthKm: number | null;
  lastEventAt: string | null;
  closestEvent: { id: string; distanceKm: number; magnitude: number; occurredAt: string } | null;
}

// ─────────────────────────────────────────────────────────────
// Regions (city polygon, sea polygon, districts)
// ─────────────────────────────────────────────────────────────

export type RegionKind = 'city' | 'sea' | 'district' | 'zone';

export interface Region {
  id: string;
  slug: string;
  name: string;
  kind: RegionKind;
  /** Approximate polygon (city / sea). */
  geometry: PolygonGeometry | null;
  centroid: { latitude: number; longitude: number };
  radiusKm: number | null;
  approximate: boolean;
  source: string;
}

export interface RegionStats {
  slug: string;
  name: string;
  kind: RegionKind;
  counts: { h24: number; d7: number; d30: number };
  maxMagnitude: number | null;
  avgMagnitude: number | null;
  avgDepthKm: number | null;
  lastEventAt: string | null;
  nearestEvent: { id: string; distanceKm: number; magnitude: number; occurredAt: string } | null;
}

// ─────────────────────────────────────────────────────────────
// Queries & pagination
// ─────────────────────────────────────────────────────────────

export type TimeRange = '1h' | '6h' | '24h' | '7d' | '30d';
export const TIME_RANGES: TimeRange[] = ['1h', '6h', '24h', '7d', '30d'];

export interface EarthquakeQuery {
  from?: string;
  to?: string;
  range?: TimeRange;
  minMagnitude?: number;
  maxMagnitude?: number;
  minDepth?: number;
  maxDepth?: number;
  source?: SourceId | 'ALL';
  region?: string;
  faultId?: string;
  search?: string;
  order?: 'time_desc' | 'time_asc' | 'magnitude_desc';
  limit?: number;
  offset?: number;
}

export interface Paginated<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

// ─────────────────────────────────────────────────────────────
// Aggregations
// ─────────────────────────────────────────────────────────────

export interface TimelineBucket {
  /** Bucket start, UTC ISO. */
  t: string;
  count: number;
  maxMagnitude: number | null;
  avgMagnitude: number | null;
  avgDepthKm: number | null;
}

export interface DistributionBin {
  /** Human label of the bin (e.g. "M2–3", "5–10 km", "Kadıköy"). */
  label: string;
  /** Machine key (bin lower bound or slug). */
  key: string;
  count: number;
  maxMagnitude?: number | null;
}

export type DistributionKind = 'magnitude' | 'depth' | 'fault' | 'district' | 'hour' | 'day';

export interface ScatterPoint {
  id: string;
  t: string;
  magnitude: number;
  depthKm: number;
}

export interface DashboardStats {
  counts: { h1: number; h24: number; d7: number; d30: number };
  maxMagnitude24h: { value: number; event: Earthquake | null } | null;
  avgDepthKm24h: number | null;
  nearestToIstanbul24h: { distanceKm: number; event: Earthquake } | null;
  lastEventAt: string | null;
  generatedAt: string;
}

// ─────────────────────────────────────────────────────────────
// Activity index (NOT a prediction)
// ─────────────────────────────────────────────────────────────

export type ActivityLevel = 'LOW' | 'MODERATE' | 'ELEVATED' | 'HIGH' | 'VERY_HIGH';

export interface ActivityComponents {
  frequency: number;
  magnitude: number;
  recency: number;
  clustering: number;
  depth: number;
}

export interface ActivitySnapshot {
  region: string;
  score: number;
  level: ActivityLevel;
  components: ActivityComponents;
  computedAt: string;
  windowHours: number;
  sampleSize: number;
  /** Mandatory disclaimer, surfaced verbatim in the UI. */
  disclaimer: string;
}

export const ACTIVITY_DISCLAIMER =
  'Bu değer deprem tahmini değildir. Yalnızca gözlenen geçmiş ve mevcut verinin istatistiksel yoğunluğunu gösterir.';

export function activityLevelForScore(score: number): ActivityLevel {
  if (score < 20) return 'LOW';
  if (score < 40) return 'MODERATE';
  if (score < 60) return 'ELEVATED';
  if (score < 80) return 'HIGH';
  return 'VERY_HIGH';
}

// ─────────────────────────────────────────────────────────────
// System / observability
// ─────────────────────────────────────────────────────────────

export interface DataSourceStatus {
  id: SourceId;
  name: string;
  enabled: boolean;
  status: SourceHealth;
  lastSuccessAt: string | null;
  lastErrorAt: string | null;
  lastError: string | null;
  latencyMs: number | null;
  errorCount: number;
  attribution: string;
  url: string;
}

export interface IngestionRun {
  id: string;
  source: SourceId;
  startedAt: string;
  finishedAt: string | null;
  status: 'RUNNING' | 'SUCCESS' | 'PARTIAL' | 'ERROR';
  fetched: number;
  inserted: number;
  updated: number;
  merged: number;
  invalid: number;
  error: string | null;
}

export interface SystemEvent {
  id: string;
  at: string;
  level: 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';
  service: string;
  event: string;
  message: string;
  context?: Record<string, unknown>;
}

export interface SystemStatus {
  status: 'ok' | 'degraded';
  time: string;
  uptimeSeconds: number;
  version: string;
  environment: string;
  database: { mode: 'postgres' | 'memory'; ok: boolean; latencyMs: number | null };
  cache: { mode: 'redis' | 'memory'; ok: boolean };
  websocket: { clients: number };
  ingestion: {
    mode: 'embedded' | 'worker' | 'unknown';
    lastRunAt: string | null;
    lastSuccessAt: string | null;
  };
}

// ─────────────────────────────────────────────────────────────
// WebSocket protocol
// ─────────────────────────────────────────────────────────────

export interface WsHello {
  type: 'hello';
  serverTime: string;
  message: string;
}
export interface WsHeartbeat {
  type: 'heartbeat';
  serverTime: string;
}
export interface WsEarthquakeNew {
  type: 'earthquake:new';
  data: Earthquake;
}
export interface WsEarthquakeUpdated {
  type: 'earthquake:updated';
  data: Earthquake;
}
export interface WsSourcesStatus {
  type: 'sources:status';
  data: DataSourceStatus[];
}
export interface WsActivityUpdate {
  type: 'activity:update';
  data: ActivitySnapshot[];
}

export type WsServerEvent =
  | WsHello
  | WsHeartbeat
  | WsEarthquakeNew
  | WsEarthquakeUpdated
  | WsSourcesStatus
  | WsActivityUpdate;

/** Events forwarded over the internal bus between worker and API. */
export type BusEvent = WsEarthquakeNew | WsEarthquakeUpdated | WsSourcesStatus | WsActivityUpdate;

// ─────────────────────────────────────────────────────────────
// Search
// ─────────────────────────────────────────────────────────────

export interface SearchResult {
  earthquakes: Earthquake[];
  faults: Pick<FaultSegment, 'id' | 'slug' | 'name' | 'segmentType'>[];
  regions: Pick<Region, 'slug' | 'name' | 'kind'>[];
}

// ─────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────

export function rangeToMs(range: TimeRange): number {
  switch (range) {
    case '1h':
      return 3_600_000;
    case '6h':
      return 21_600_000;
    case '24h':
      return 86_400_000;
    case '7d':
      return 7 * 86_400_000;
    case '30d':
      return 30 * 86_400_000;
  }
}

/** Recommended aggregation bucket (ms) per requested range — backend-side aggregation. */
export function bucketForRange(range: TimeRange): number {
  switch (range) {
    case '1h':
      return 5 * 60_000;
    case '6h':
      return 15 * 60_000;
    case '24h':
      return 3_600_000;
    case '7d':
      return 6 * 3_600_000;
    case '30d':
      return 24 * 3_600_000;
  }
}
